//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT100720_59130033.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KT100720_59130033Entities : DbContext
    {
        public KT100720_59130033Entities()
            : base("name=KT100720_59130033Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LOAIT> LOAITS { get; set; }
        public virtual DbSet<TAISAN> TAISANs { get; set; }
    
        public virtual int TaiSan_TimKiem(string maTS, string tenTS)
        {
            var maTSParameter = maTS != null ?
                new ObjectParameter("MaTS", maTS) :
                new ObjectParameter("MaTS", typeof(string));
    
            var tenTSParameter = tenTS != null ?
                new ObjectParameter("TenTS", tenTS) :
                new ObjectParameter("TenTS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TaiSan_TimKiem", maTSParameter, tenTSParameter);
        }
    }
}
