//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT100720_59130033.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAISAN
    {
        public string MaTS { get; set; }
        public string TenTS { get; set; }
        public string DVT { get; set; }
        public Nullable<bool> XuatXu { get; set; }
        public int DonGia { get; set; }
        public string AnhMH { get; set; }
        public string GhiChu { get; set; }
        public string MaLTS { get; set; }
    
        public virtual LOAIT LOAIT { get; set; }
    }
}
